[project]
name = "hello-honey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "honey",
]

[tool.uv.sources]
honey = { path = "../honey", editable = true }
